# Generated by Django 2.2.23 on 2021-05-21 11:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.IntegerField()),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'vw_visitor_report',
                'ordering': ['visit_count'],
                'managed': False,
            },
        ),
    ]
