# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='cloud_mean',
            new_name='cloud_max',
        ),
        migrations.AddField(
            model_name='search',
            name='cloud_min',
            field=models.IntegerField(blank=True, max_length=3, null=True, verbose_name=b'Min Clouds'),
        ),
    ]
