# Generated by Django 2.2.28 on 2022-07-06 22:16

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionaries', '__first__'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUsersMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_earth_obeservation', models.CharField(max_length=255, verbose_name='Person in charge for Earth Observation')),
                ('email_earth_observation', models.CharField(max_length=255, verbose_name='Email for Earth Observation')),
                ('phone_earth_observation', models.CharField(max_length=255, verbose_name='Phone for Earth Observation')),
                ('catalogue_email_enqueries', models.CharField(max_length=255, verbose_name='Catalogue Email for Enqueries')),
                ('catalogue_phone', models.CharField(max_length=255, verbose_name='Catalogue Telphone for Enqueries')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='GenericProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_date', models.DateTimeField(db_index=True)),
                ('spatial_coverage', django.contrib.gis.db.models.fields.PolygonField(help_text='Image footprint', srid=4326)),
                ('original_product_id', models.CharField(help_text='Original id assigned to the product by the vendor/operator', max_length=255, unique=True)),
                ('unique_product_id', models.CharField(blank=True, help_text='A unique identifier for product used internally e.g. for DIMS orders', max_length=255, null=True)),
                ('local_storage_path', models.CharField(blank=True, help_text='Location on local storage if this product is offered for immediate download.', max_length=255, null=True)),
                ('metadata', models.TextField(help_text='An xml document describing all known metadata for this product.')),
                ('ingestion_log', models.TextField(help_text='The log of ingestion events (written programmatically to this field by ingestors. Stored in chronological order by appending to the bottom of this text field.')),
                ('remote_thumbnail_url', models.TextField(blank=True, help_text="Location on a remote server where this product's thumbnail resides. The value in this field will be nulled when a local copy is made of the thumbnail.", max_length=255, null=True)),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Projection')),
                ('quality', models.ForeignKey(help_text='A quality assessment describing the amount of dropouts etc.and how usable the entire scene is.', on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Quality')),
            ],
            options={
                'ordering': ('-product_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Slide Name')),
                ('slide', models.ImageField(blank=True, null=True, upload_to='images/slider/')),
            ],
        ),
        migrations.CreateModel(
            name='WorldBorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='GenericImageryProduct',
            fields=[
                ('genericproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.GenericProduct')),
                ('spatial_resolution', models.FloatField(help_text='Spatial resolution in m')),
                ('spatial_resolution_x', models.FloatField(help_text='Spatial resolution in m (x direction)')),
                ('spatial_resolution_y', models.FloatField(help_text='Spatial resolution in m (y direction)')),
                ('radiometric_resolution', models.IntegerField(help_text='Bit depth of image e.g. 16bit Note that this is for the delivered image and not necessarily the same as bit depth at acquisition.')),
                ('band_count', models.IntegerField(help_text='Number of spectral bands in product')),
            ],
            bases=('catalogue.genericproduct',),
        ),
        migrations.CreateModel(
            name='OrdinalProduct',
            fields=[
                ('genericproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.GenericProduct')),
                ('class_count', models.IntegerField(help_text='Number of spectral bands in product')),
                ('confusion_matrix', models.CharField(blank=True, help_text='Confusion matrix in the format: true positive, false negative, false positive,true negative', max_length=80, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('kappa_score', models.FloatField(blank=True, help_text='Enter a value between 0 and 1 representing the kappa score.', null=True)),
            ],
            bases=('catalogue.genericproduct',),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('ip_position', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='IP Lat/Long')),
                ('visit_date', models.DateTimeField(auto_now=True, verbose_name='DateAdded')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'ordering': ('visit_date',),
            },
        ),
        migrations.CreateModel(
            name='GenericSensorProduct',
            fields=[
                ('genericimageryproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.GenericImageryProduct')),
                ('product_acquisition_start', models.DateTimeField(db_index=True)),
                ('product_acquisition_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('geometric_accuracy_mean', models.FloatField(blank=True, db_index=True, null=True)),
                ('geometric_accuracy_1sigma', models.FloatField(blank=True, null=True)),
                ('geometric_accuracy_2sigma', models.FloatField(blank=True, null=True)),
                ('radiometric_signal_to_noise_ratio', models.FloatField(blank=True, null=True)),
                ('radiometric_percentage_error', models.FloatField(blank=True, null=True)),
                ('spectral_accuracy', models.FloatField(blank=True, help_text='Wavelength Deviation - a static figure that normally does not change for a given sensor.', null=True)),
                ('orbit_number', models.IntegerField(blank=True, null=True)),
                ('path', models.IntegerField(blank=True, db_index=True, null=True)),
                ('path_offset', models.IntegerField(blank=True, db_index=True, null=True)),
                ('row', models.IntegerField(blank=True, null=True)),
                ('row_offset', models.IntegerField(blank=True, null=True)),
                ('offline_storage_medium_id', models.CharField(blank=True, help_text='Identifier for the offline tape or other medium on which this scene is stored', max_length=12, null=True)),
                ('online_storage_medium_id', models.CharField(blank=True, help_text='DIMS Product Id as defined by Werum e.g. S5_G2_J_MX_200902160841252_FG_001822', max_length=36, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('catalogue.genericimageryproduct',),
        ),
        migrations.CreateModel(
            name='GeospatialProduct',
            fields=[
                ('genericproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.GenericProduct')),
                ('name', models.CharField(help_text='A descriptive name for this dataset', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the product', null=True)),
                ('processing_notes', models.TextField(blank=True, help_text='Description of how the product was created.', null=True)),
                ('equivalent_scale', models.IntegerField(blank=True, default=1000000, help_text='The fractional part at the ideal maximum scale for this dataset. For example enter "50000" if it should not be used at scales larger that 1:50 000', null=True)),
                ('data_type', models.CharField(blank=True, choices=[('RA', 'Raster'), ('VP', 'Vector - Points'), ('VL', 'Vector - Lines'), ('VA', 'Vector - Areas / Polygons')], help_text='Is this a vector or raster dataset?', max_length=2, null=True)),
                ('temporal_extent_start', models.DateTimeField(db_index=True, help_text='The start of the timespan covered by this dataset. If left blank will default to time of accession.')),
                ('temporal_extent_end', models.DateTimeField(blank=True, db_index=True, help_text='The start of the timespan covered by this dataset. If left blankwill default to start date.', null=True)),
                ('place', models.ForeignKey(help_text='Nearest place, town, country region etc. to this product', on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Place')),
                ('place_type', models.ForeignKey(help_text='Select the type of geographic region covered by this dataset', on_delete=django.db.models.deletion.CASCADE, to='dictionaries.PlaceType')),
                ('primary_topic', models.ForeignKey(help_text='Select the most appopriate topic for this dataset. You can add additional keywords in the tags box.', on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Topic')),
            ],
            bases=('catalogue.genericproduct',),
        ),
        migrations.CreateModel(
            name='ContinuousProduct',
            fields=[
                ('genericproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.GenericProduct')),
                ('range_min', models.FloatField(help_text='The minimum value in the range of values represented in this dataset.')),
                ('range_max', models.FloatField(help_text='The maximum value in the range of values represented in thisdataset.')),
                ('unit', models.ForeignKey(help_text='Units for the values represented in this dataset.', on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Unit')),
            ],
            bases=('catalogue.genericproduct',),
        ),
        migrations.CreateModel(
            name='RadarProduct',
            fields=[
                ('genericsensorproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.GenericSensorProduct')),
                ('imaging_mode', models.CharField(blank=True, max_length=200, null=True)),
                ('look_direction', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True)),
                ('antenna_receive_configuration', models.CharField(blank=True, choices=[('V', 'Vertical'), ('H', 'Horizontal')], max_length=1, null=True)),
                ('polarising_mode', models.CharField(blank=True, choices=[('S', 'Single Pole'), ('D', 'Dual Pole'), ('Q', 'Quad Pole')], max_length=1, null=True)),
                ('polarising_list', models.CharField(blank=True, help_text='Comma separated list of V/H/VV/VH/HV/HH (vertical and horizontal polarisation.)', max_length=200, null=True)),
                ('slant_range_resolution', models.FloatField(blank=True, null=True)),
                ('azimuth_range_resolution', models.FloatField(blank=True, null=True)),
                ('orbit_direction', models.CharField(blank=True, choices=[('A', 'Ascending'), ('D', 'Descending')], max_length=1, null=True)),
                ('calibration', models.CharField(blank=True, max_length=255, null=True)),
                ('incidence_angle', models.FloatField(blank=True, null=True)),
                ('product_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.RadarProductProfile')),
            ],
            bases=('catalogue.genericsensorproduct',),
        ),
        migrations.CreateModel(
            name='OpticalProduct',
            fields=[
                ('genericsensorproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.GenericSensorProduct')),
                ('cloud_cover', models.IntegerField(blank=True, help_text='The maximum cloud cover when searching for images. Note that not all sensors support cloud cover filtering. Range 0-100%', null=True)),
                ('sensor_inclination_angle', models.FloatField(blank=True, help_text='Orientation of the vehicle on which the sensor is mounted', null=True)),
                ('sensor_viewing_angle', models.FloatField(blank=True, help_text='Angle of acquisition for the image', null=True)),
                ('gain_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gain_value_per_channel', models.CharField(blank=True, help_text='Comma separated list of gain values', max_length=200, null=True)),
                ('gain_change_per_channel', models.CharField(blank=True, help_text='Comma separated list of gain change values', max_length=200, null=True)),
                ('bias_per_channel', models.CharField(blank=True, help_text='Comma separated list of bias values', max_length=200, null=True)),
                ('solar_zenith_angle', models.FloatField(blank=True, null=True)),
                ('solar_azimuth_angle', models.FloatField(blank=True, null=True)),
                ('earth_sun_distance', models.FloatField(blank=True, null=True)),
                ('product_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.OpticalProductProfile')),
            ],
            bases=('catalogue.genericsensorproduct',),
        ),
    ]
