# Generated by Django 2.2.28 on 2025-03-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_allusersmessage_contact_continuousproduct_genericimageryproduct_genericproduct_genericsensorproduct_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericproduct',
            name='projection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Projection'),
        ),
        migrations.AlterField(
            model_name='genericproduct',
            name='quality',
            field=models.ForeignKey(help_text='A quality assessment describing the amount of dropouts etc.and how usable the entire scene is.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Quality'),
        ),
    ]
