BEGIN;
ALTER SEQUENCE catalogue_clip_id_seq RENAME TO search_clip_id_seq;
ALTER SEQUENCE catalogue_search_id_seq RENAME TO search_search_id_seq;
ALTER SEQUENCE catalogue_searchdaterange_id_seq RENAME TO search_searchdaterange_id_seq;
ALTER SEQUENCE catalogue_searchrecord_id_seq RENAME TO search_searchrecord_id_seq;

-- old dictionaries
ALTER SEQUENCE catalogue_projection_id_seq RENAME TO dictionaries_projection_id_seq;
ALTER SEQUENCE catalogue_institution_id_seq RENAME TO dictionaries_institution_id_seq;
ALTER SEQUENCE catalogue_license_id_seq RENAME TO dictionaries_license_id_seq;
ALTER SEQUENCE catalogue_quality_id_seq RENAME TO dictionaries_quality_id_seq;
ALTER SEQUENCE catalogue_topic_id_seq RENAME TO dictionaries_topic_id_seq;
ALTER SEQUENCE catalogue_placetype_id_seq RENAME TO dictionaries_placetype_id_seq;
ALTER SEQUENCE catalogue_place_id_seq RENAME TO dictionaries_place_id_seq;
ALTER SEQUENCE catalogue_unit_id_seq RENAME TO dictionaries_unit_id_seq;

COMMIT;