# Generated by Django 2.2.27 on 2022-05-06 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionaries', '__first__'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Datums',
                'verbose_name_plural': 'Datums',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Delivery Method',
                'verbose_name_plural': 'Delivery Methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'File Format',
                'verbose_name_plural': 'File Formats',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Make a note of any special requirements or processing instructions (including processing levels). Please note that in the case of free products and priority products, they will only be supplied with default options.', null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, help_text='When the order was placed - not shown to users', verbose_name='Order Date')),
                ('datum', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Datum', verbose_name='Datum')),
                ('delivery_method', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.DeliveryMethod', verbose_name='Delivery Method')),
                ('file_format', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.FileFormat', verbose_name='File Format')),
                ('market_sector', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.MarketSector')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Status List',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResamplingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Resampling Method',
                'verbose_name_plural': 'Resampling Methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_change_date', models.DateTimeField(auto_now_add=True, help_text='When the order status was changed', verbose_name='Date')),
                ('notes', models.TextField()),
                ('new_order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_order_status', to='orders.OrderStatus', verbose_name='New Order Status')),
                ('old_order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_order_status', to='orders.OrderStatus', verbose_name='Old Order Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status History',
                'ordering': ('-order_change_date',),
            },
        ),
        migrations.CreateModel(
            name='OrderNotificationRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ManyToManyField(blank=True, help_text='Please subscribe to one or more product class. Use ctrl-click to select more than one.', to='contenttypes.ContentType', verbose_name='Product classes')),
                ('satellite_instrument_group', models.ManyToManyField(blank=True, help_text='Please choose one or more SatelliteInstrument. Use ctrl-clickto select more than one.', to='dictionaries.SatelliteInstrumentGroup', verbose_name='SatelliteInstrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Notification Recipient',
                'verbose_name_plural': 'Order Notification Recipients',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderStatus', verbose_name='Order Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='resampling_method',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='orders.ResamplingMethod', verbose_name='Resampling Method'),
        ),
        migrations.AddField(
            model_name='order',
            name='subsidy_type_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_type+', to='dictionaries.SubsidyType'),
        ),
        migrations.AddField(
            model_name='order',
            name='subsidy_type_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_type+', to='dictionaries.SubsidyType'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NonSearchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.CharField(help_text='Description of an ordered product', max_length=100)),
                ('download_path', models.CharField(help_text='This is the location from where the product can be downloaded after a successfull OS4EO order placement.', max_length=512)),
                ('cost_per_scene', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rand_cost_per_scene', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.Currency')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
