# Generated by Django 2.2.28 on 2022-07-06 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_uses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='uses',
            new_name='uses_of_the_data',
        ),
    ]
