#!/bin/bash

# This is intended to be placed in the docker dev environment so
# that the django project is in the path when you log in

if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi
export PYTHONPATH=/home/web/django_project:$PYTHONPATH
export DJANGO_SETTINGS_MODULE=core.settings.dev_docker
cd /home/web/django_project

export DATABASE_NAME=gis
export DATABASE_USERNAME=docker
export DATABASE_PASSWORD=docker
export DATABASE_HOST=db
export DJANGO_SETTINGS_MODULE=core.settings.prod_docker
export PYTHONPATH=/home/web/django_project
export VIRTUAL_HOST=catalgue
export VIRTUAL_PORT=8080
