var DestroyFeatures=OpenLayers.Class(OpenLayers.Control,{type:OpenLayers.Control.TYPE_BUTTON,trigger:function(){this.layer.destroyFeatures()}});OpenLayers.Renderer.VML.prototype.supported=function(){return OpenLayers.Util.getBrowserName()=="msie"};OpenLayers.Renderer.VML.prototype.initialize=function(){OpenLayers.Renderer.Elements.prototype.initialize.apply(this,arguments)};
var mSceneStyleMap=new OpenLayers.StyleMap(OpenLayers.Util.applyDefaults({fillColor:"#000000",fillOpacity:0,strokeColor:"yellow",graphicZIndex:"${zIndex}"},OpenLayers.Feature.Vector.style["default"])),mDrawingStyleLookup={yes:{strokeColor:"red"},no:{strokeColor:"yellow"}},mContext=function(a){return a};mSceneStyleMap.addUniqueValueRules("default","selected",mDrawingStyleLookup,mContext);var mNavigationPanel=null,mMapControls=null,mWKTFormat=null,mVectorLayer=null,mMap=null;
$(document).ready(function(){setupSceneIdHelpDialog();$(".blocking-link").live("click",block)});function unblock(){$.unblockUI()}function block(){$.blockUI({message:'<h2><img src="/media/images/ajax-loader.gif" /> Loading...</h2>',css:{border:"1px solid #000",padding:"15px",backgroundColor:"#fff","-webkit-border-radius":"10px","-moz-border-radius":"10px",opacity:0.9,color:"#000"}})}
function getLayerByName(a){if(!mMap)return false;myLayers=mMap.getLayersByName(a);return myLayers.length>0?myLayers[0]:false}function readWKT(a){var b=/^SRID=\d+;(.+)/i.exec(a);if(b)a=b[1];if(a=mWKTFormat.read(a))return a.geometry}function writeWKT(a){myGeometry=a.clone();myUnprojectedGeometry=reverseTransformGeometry(myGeometry);document.getElementById("id_geometry").value="SRID=4326;"+mWKTFormat.write(new OpenLayers.Feature.Vector(myUnprojectedGeometry))}
function addWKT(a){if(mVectorLayer.features.length>1){myOldFeatures=[mVectorLayer.features[0]];mVectorLayer.removeFeatures(myOldFeatures);mVectorLayer.destroyFeatures(myOldFeatures)}writeWKT(a.feature.geometry)}function modifyWKT(a){writeWKT(a.feature.geometry)}function addSelectControl(){var a=new OpenLayers.Control.SelectFeature(mVectorLayer,{toggle:true,clickout:true});mMap.addControl(a);a.activate();mVectorLayer.selectFeatureControl=a}
function enableDrawing(){mMap.getControlsByClass("OpenLayers.Control.DrawFeature")[0].activate()}function enableEditing(){mMap.getControlsByClass("OpenLayers.Control.ModifyFeature")[0].activate()}
function setupEditingPanel(a){var b=new OpenLayers.Control.DrawFeature(a,OpenLayers.Handler.Polygon,{displayClass:"olControlDrawFeaturePolygon"}),c=new OpenLayers.Control.ModifyFeature(a,{displayClass:"olControlModifyFeature"});a=new DestroyFeatures({displayClass:"destroyFeature",layer:a});mMapControls=[b,c,a];mNavigationPanel.addControls(mMapControls)}function zebraTables(){$("table tr:even").addClass("odd");$("table tr:odd").addClass("even")}
$(function(){$("#accordion").accordion({autoHeight:false});zebraTables()});function clearSearchResults(){myLayer=getLayerByName("scenes");if(myLayer!==false){var a=myLayer.selectFeatureControl;if(a){a.deactivate();myLayer.map.removeControl(a)}myLayer.destroy()}}
function prepareFancy(){$("#accordion").accordion("activate",1);$("a#large_preview").fancybox({overlayShow:false,imageScale:true,zoomSpeedIn:600,zoomSpeedOut:500,easingIn:"easeOutBack",easingOut:"easeInBack",frameWidth:500,frameHeight:500})}
function showMiniCart(){myShowAccordionFlag=true;if(arguments.length==1)myShowAccordionFlag=arguments[0];myLayer=mMap.getLayersByName("Cart")[0];myLayer.mergeNewParams({seed:Math.random()});myLayer.redraw();$("#cart").load("/showminicartcontents/","",zebraTables);myShowAccordionFlag&&$("#accordion").accordion("activate",2);$("#working").slideUp("slow")}
function addToCart(a){$("#working").html('<p>Adding, please wait...<img src="/media/images/ajax-loader.gif"></p>');$("#working").slideDown("slow");$.get("/addtocart/"+a+"/?xhr","",showMiniCart);return false}function layerRemoved(){myLayer=mMap.getLayersByName("Cart")[0];myLayer.mergeNewParams({version:Math.random()});myLayer.redraw();$("#working").toggle("slide");return false}
function removeFromCart(a,b){$.get("/removefromcart/"+a+"/?xhr","",layerRemoved);b.parent().parent().remove();var c=$("#cart-contents-table tr").length-1;$("#cart-item-count").html(c);c<1&&$("#id_processing_level").length!=0&&window.location.replace("/emptyCartHelp/");return false}function removeFromMiniCart(a,b){$("#working").html('<p>Removing, please wait...<img src="/media/images/ajax-loader.gif"></p>');$("#working").slideDown("slow");removeFromCart(a,b)}
function showCart(){$("#cart").load("/showcartcontents/","",zebraTables);$("#working").slideUp("slow")}function getElement(a){return document.getElementById?document.getElementById(a):document.all?document.all[a]:document.layers?document.layers[a]:0}function getFeatureByProductId(a){myLayer=getLayerByName("scenes");if(myLayer!==false)for(var b=myLayer.features,c=0;c<b.length;++c)if(b[c].product_id==a)return c;return-1}
function revealTable(){zebraTables();$("#working").slideUp("slow");$("#working").html("");$("#table").slideDown("slow")}function loadPage(a,b){$("#table").slideUp("slow");$("#working").html('<p>Loading, please wait...<img src="/media/images/ajax-loader.gif"></p>');$("#working").slideDown("slow");$("#results-table").parent().load("/searchpage/"+b+"/?page="+a,"",revealTable)}
function resizeTable(){myWindowHeight=$(window).height();myHeaderHeight=$("#header").height();myMapHeight=$("#map").height();myFooterHeight=$("#footer").height();myPadding=140;myTableHeight=myWindowHeight-(myHeaderHeight+myFooterHeight+myMapHeight+myPadding);if(myTableHeight<200)myTableHeight=200;$("#results-table").height(myTableHeight)}
function showFeatureInfo(a){$("#working").html('<p>Adding, please wait...<img src="/media/images/ajax-loader.gif"></p>');$("#working").slideDown("slow");myMousePos=mMap.getLonLatFromPixel(a.xy);myBoundingBox=mMap.getExtent().toBBOX();myPixelX=a.xy.x;myPixelY=a.xy.y;myMapWidth=mMap.size.w;myMapHeight=mMap.size.h;$("#mapquery").slideDown("slow");$("#hidemapquery").live("click",function(){$("#mapquery").slideUp("slow")});$.get("/getFeatureInfo/"+myMousePos.lon+"/"+myMousePos.lat+"/"+myBoundingBox+"/"+
myPixelX+"/"+myPixelY+"/"+myMapWidth+"/"+myMapHeight+"/",function(b){$("#mapquery").html("<p><input type=button id='hidemapquery' value='Hide'></p>"+b)});Event.stop(a);$("#working").slideUp("slow")}function setHTML(a){$("#mapquery").html("<p><input type=button id='hidemapquery' value='Hide'></p>"+a.responseText);$("#mapquery").slideDown("slow");$("#hidemapquery").click(function(){$("#mapquery").slideUp("slow")})}
function createLegend(){myLayers=mMap.layers;for(var a=0;a<myLayers.length;a++){myLayer=myLayers[a];myLayerName=myLayer.name;myVisibility=myLayer.visibility;myCheckedString="";if(myVisibility)myCheckedString="checked";if(myLayer.isBaseLayer){myLegendItem='<li class="ui-corner-all button ui-button ui-widget ui-button-text-only ui-state-default"><input id="'+myLayerName+'-radiobutton" name="backdrop-layers" type="radio" value="'+myLayerName+'" '+myCheckedString+'/><label forname="'+myLayerName+'-radiobutton">'+
myLayerName+"</label></li>";$("#base-layer-legend").append(myLegendItem)}}$(":radio").change(function(){myLayer=getLayerByName(this.value);mMap.setBaseLayer(myLayer)})}
function setupCloudSlider(){$("#id_cloud_meanSlider").slider({value:5,min:0,max:10,step:1,start:function(){$("#id_cloud_meanSliderBubble").fadeIn("fast")},stop:function(){$("#id_cloud_meanSliderBubble").fadeOut("fast")},slide:function(a,b){var c=$("#id_cloud_meanSlider").width()/10*b.value;$("#id_cloud_meanSliderHandle").css("left",c);$("#id_cloud_mean").val(b.value);$("#id_cloud_meanSliderBubble").css("left",c).text(b.value*10+"%")}});$("#id_cloud_mean").val($("#id_cloud_meanSlider").slider("value"));
$("#id_cloud_meanSliderBubble").html($("#id_cloud_meanSlider").slider("value")*10+"%");unblock()}
function setupBaseMap(){var a={projection:new OpenLayers.Projection("EPSG:900913"),displayProjection:new OpenLayers.Projection("EPSG:4326"),units:"m",maxResolution:156543.0339,maxExtent:new OpenLayers.Bounds(-2.003750834E7,-2.003750834E7,2.003750834E7,2.003750834E7),numZoomLevels:18,controls:[]};mMap=new OpenLayers.Map("map",a);mNavigationPanel=new OpenLayers.Control.Panel({div:document.getElementById("map-navigation-panel")});a=new OpenLayers.Control.ZoomBox({title:"Zoom in box",displayClass:"olControlZoomBoxIn",
out:false});mMap.addControl(a);var b=new OpenLayers.Control.ZoomBox({title:"Zoom in box",displayClass:"olControlZoomBoxOut",out:true});mMap.addControl(b);var c=new OpenLayers.Control.Navigation;mMap.addControl(c);var d=new OpenLayers.Control.NavigationHistory;mMap.addControl(d);mNavigationPanel.addControls([a,b,c,d.next,d.previous]);mMap.addControl(new OpenLayers.Control.ScaleBar({align:"left",minWidth:150,maxWidth:200,div:document.getElementById("map-scale")}));mMap.addControl(new OpenLayers.Control.MousePosition({div:document.getElementById("map-location")}));
mMap.addControl(mNavigationPanel)}
function setupSearchMap(a){$("#advancedSearch").live("click",function(){block();$("#search-panel").load("/search/?advanced",setupCloudSlider,null)});$("#simpleSearch").live("click",function(){block();$("#search-panel").load("/search/",setupCloudSlider,null)});$("#id_cloud_mean").length>0&&setupCloudSlider();mWKTFormat=new OpenLayers.Format.WKT;setupBaseMap();mVectorLayer=new OpenLayers.Layer.Vector("geometry");mMap.addLayer(mVectorLayer);setupEditingPanel(mVectorLayer);mMap.addLayers(a);addSelectControl();
mMap.addControl(new OpenLayers.Control.LayerSwitcher);if(a=document.getElementById("id_geometry").value){var b=readWKT(a);b=transformGeometry(b);writeWKT(b);mVectorLayer.addFeatures([new OpenLayers.Feature.Vector(b)]);mMap.zoomToExtent(b.getBounds())}else{b=new OpenLayers.Bounds(16.3477,-35.2411,33.3984,-21.9727);b.transform(new OpenLayers.Projection("EPSG:4326"),new OpenLayers.Projection("EPSG:900913"));mMap.zoomToExtent(b)}mVectorLayer.events.on({featuremodified:modifyWKT});mVectorLayer.events.on({featureadded:addWKT});
a?enableEditing():enableDrawing();createLegend()}
function setupTaskingMap(a){mWKTFormat=new OpenLayers.Format.WKT;mVectorLayer=new OpenLayers.Layer.Vector("geometry");mMap.addLayer(mVectorLayer);setupEditingPanel(mVectorLayer);layerMapnik=new OpenLayers.Layer.OSM.Mapnik("Open Street Map");a.push(layerMapnik);mMap.addLayers(a);addSelectControl();mMap.addControl(new OpenLayers.Control.LayerSwitcher);if(a=document.getElementById("id_geometry").value){var b=readWKT(a);b=transformGeometry(b);writeWKT(b);mVectorLayer.addFeatures([new OpenLayers.Feature.Vector(b)]);
mMap.zoomToExtent(b.getBounds())}else{b=new OpenLayers.Bounds(16.3477,-35.2411,33.3984,-21.9727);b.transform(new OpenLayers.Projection("EPSG:4326"),new OpenLayers.Projection("EPSG:900913"));mMap.zoomToExtent(b)}mVectorLayer.events.on({featuremodified:modifyWKT});mVectorLayer.events.on({featureadded:addWKT});a?enableEditing():enableDrawing();createLegend()}function featureSelected(a){$("#working").html(a.feature.product_id);$("#working").slideDown("slow");hightlightRecord(a.feature.id,false)}
function setupSceneSelector(a){var b=new OpenLayers.Control.SelectFeature(a,{hover:false,highlightOnly:true,renderIntent:"temporary",eventListeners:{beforefeaturehighlighted:null,featurehighlighted:featureSelected,featureunhighlighted:null}});mMap.addControl(b);b.activate();a.selectFeatureControl=b}function deleteFeatures(){mVectorLayer.removeFeatures(mVectorLayer.features);mVectorLayer.destroyFeatures()}
function clearFeatures(){deleteFeatures();document.getElementById("id_geometry").value="";mMap.setCenter(transformPoint(new OpenLayers.LonLat(0,0)),4)}
function setupSearchFeatureInfo(){var a=new OpenLayers.Control.WMSGetFeatureInfo({url:"http://196.35.94.243/cgi-bin/mapserv?map=SEARCHES",title:"Identify features by clicking",queryVisible:true,vendorParams:{FEATURE_COUNT:"1000",INFO_FORMAT:"text/html"},eventListeners:{getfeatureinfo:function(b){b.text.length>1?mMap.addPopup(new OpenLayers.Popup.FramedCloud("chicken",mMap.getLonLatFromPixel(b.xy),null,b.text,null,true)):mMap.addPopup(new OpenLayers.Popup.FramedCloud("chicken",mMap.getLonLatFromPixel(b.xy),
null,"No result *sniff*",null,true))}}});mMap.addControl(a);a.activate()}function setupSqlDialog(){$("#sql-button").live("click",function(){$("#sql").dialog({modal:true,show:"slide",width:600,hide:"slide",autoOpen:true,zIndex:9999,title:"Underlying Query:",buttons:{Close:function(){$(this).dialog("close")}}})})}
function setupSceneIdHelpDialog(){var a=$("<div></div>").load("/sceneidhelp/").dialog({autoOpen:false,title:"Scene Id Help",modal:true,show:"slide",hide:"slide",zIndex:9999,height:$(window).height()/2,width:$(window).width()/2,buttons:{Close:function(){$(this).dialog("close")}}});$("#scene-id-help").live("click",function(){a.dialog("open");return false})}
function setupMapHelpDialog(){var a=$("<div></div>").load("/mapHelp/").dialog({autoOpen:false,title:"Map Help",modal:true,show:"slide",hide:"slide",zIndex:9999,height:$(window).height()/2,width:$(window).width()/2,buttons:{Close:function(){$(this).dialog("close")}}});$("#map-help-button").live("click",function(){a.dialog("open");return false})}
function showMetadata(a){$("<div></div>").load("/metadata/"+a+"/").dialog({autoOpen:true,title:"Metadata",modal:true,show:"slide",hide:"slide",zIndex:9999,height:$(window).height()/2,width:$(window).width()/2,buttons:{Close:function(){$(this).dialog("close")}}})}function setupMetadataDialog(){$(".metadata-icon").live("click",function(){var a=$(this).attr("longdesc");showMetadata(a)})}
function resetSceneZIndices(){myLayer=getLayerByName("scenes");if(myLayer!==false)for(var a=myLayer.features,b=0;b<a.length;++b){a[b].attributes.zIndex=0;a[b].selected="no"}return-1}function getFeatureIndexByRecordId(a){myLayer=getLayerByName("scenes");if(myLayer!==false)for(var b=myLayer.features,c=0;c<b.length;++c)if(b[c].id==a)return c;return-1}
function hightlightRecord(a,b){$("#preview-accordion-div").load("/showpreview/"+a+"/medium/","",prepareFancy);resetSceneZIndices();var c=getLayerByName("scenes"),d=getFeatureIndexByRecordId(a);c.features[d].attributes.zIndex=1;c.features[d].selected="yes";b&&mMap.zoomToExtent(c.features[d].geometry.bounds);c.redraw()}function setupMiniIconClickCallback(){$(".mini-icon").live("click",function(){var a=$(this).attr("longdesc");hightlightRecord(a,true)})}
function addOrderClicked(){$("#cart-contents-table tr").length<2?$("#cart-empty-dialog").dialog({modal:true,show:"blind",hide:"explode",zIndex:99999,buttons:{Ok:function(){$(this).dialog("close")}}}):window.location.replace("/addorder/");return false}function transformBounds(a){myBounds=a.clone();a=new OpenLayers.Projection("EPSG:4326");var b=mMap.getProjectionObject()||new OpenLayers.Projection("EPSG:900913");myBounds.transform(a,b);return myBounds}
function transformGeometry(a){myGeometry=a.clone();a=new OpenLayers.Projection("EPSG:4326");var b=mMap.getProjectionObject()||new OpenLayers.Projection("EPSG:900913");myGeometry.transform(a,b);return myGeometry}function reverseTransformGeometry(a){myGeometry=a.clone();a=new OpenLayers.Projection("EPSG:4326");myGeometry.transform(mMap.getProjectionObject(),a);return myGeometry}
function transformPoint(a){var b=new OpenLayers.Projection("EPSG:4326"),c=new OpenLayers.Projection("EPSG:900913");myPoint=a.clone();return myPoint=myPoint.transform(b,c)}function reverseTransformPoint(a){var b=new OpenLayers.Projection("EPSG:4326"),c=new OpenLayers.Projection("EPSG:900913");myPoint=a.clone();return myPoint=myPoint.transform(c,b)};
