var DestroyFeatures=OpenLayers.Class(OpenLayers.Control,{type:OpenLayers.Control.TYPE_BUTTON,trigger:function(){this.layer.destroyFeatures()}});OpenLayers.Renderer.VML.prototype.supported=function(){return"msie"==OpenLayers.Util.getBrowserName()};OpenLayers.Renderer.VML.prototype.initialize=function(a){OpenLayers.Renderer.Elements.prototype.initialize.apply(this,arguments)};
var mSceneStyleMap=new OpenLayers.StyleMap(OpenLayers.Util.applyDefaults({fillColor:"#000000",fillOpacity:0,strokeColor:"yellow",graphicZIndex:"${zIndex}"},OpenLayers.Feature.Vector.style["default"])),mDrawingStyleLookup={yes:{strokeColor:"red"},no:{strokeColor:"yellow"}},mContext=function(a){return a};mSceneStyleMap.addUniqueValueRules("default","selected",mDrawingStyleLookup,mContext);var mNavigationPanel=null,mMapControls=null,mWKTFormat=null,mVectorLayer=null,mMap=null,mLastSelectedRecordId=null;
$(document).ready(function(){setupSceneIdHelpDialog();$(".blocking-link").live("click",block)});function unblock(){$.unblockUI()}function block(){$.blockUI({message:'<h2><img src="/media/images/ajax-loader.gif" /> Loading...</h2>',css:{border:"1px solid #000",padding:"15px",backgroundColor:"#fff","-webkit-border-radius":"10px","-moz-border-radius":"10px",opacity:0.9,color:"#000"}})}
function getLayerByName(a){if(!mMap)return!1;myLayers=mMap.getLayersByName(a);return 0<myLayers.length?myLayers[0]:!1}function readWKT(a){var b=/^SRID=\d+;(.+)/i.exec(a);b&&(a=b[1]);if(a=mWKTFormat.read(a))return a.geometry}function writeWKT(a){myGeometry=a.clone();myUnprojectedGeometry=reverseTransformGeometry(myGeometry);document.getElementById("id_geometry").value="SRID=4326;"+mWKTFormat.write(new OpenLayers.Feature.Vector(myUnprojectedGeometry))}
function addWKT(a){1<mVectorLayer.features.length&&(myOldFeatures=[mVectorLayer.features[0]],mVectorLayer.removeFeatures(myOldFeatures),mVectorLayer.destroyFeatures(myOldFeatures));writeWKT(a.feature.geometry)}function modifyWKT(a){writeWKT(a.feature.geometry)}function addSelectControl(){var a=new OpenLayers.Control.SelectFeature(mVectorLayer,{toggle:!0,clickout:!0});mMap.addControl(a);a.activate();mVectorLayer.selectFeatureControl=a}
function enableDrawing(){mMap.getControlsByClass("OpenLayers.Control.DrawFeature")[0].activate()}function enableEditing(){mMap.getControlsByClass("OpenLayers.Control.ModifyFeature")[0].activate()}function enableNavigation(){mMap.getControlsByClass("OpenLayers.Control.Navigation")[0].activate()}
function setupEditingPanel(a){var b=new OpenLayers.Control.DrawFeature(a,OpenLayers.Handler.Polygon,{displayClass:"olControlDrawFeaturePolygon",title:"<b>Capture polygon</b> left click to add points, double click to finish capturing"}),c=new OpenLayers.Control.ModifyFeature(a,{displayClass:"olControlModifyFeature",title:"<b>Modify polygon</b> left click to move/add points, hover and press <i>delete</i> to delete points"}),a=new DestroyFeatures({displayClass:"destroyFeature",title:"<b>Delete polygon</b> deletes polygon",
layer:a});mMapControls=[b,c,a];mNavigationPanel.addControls(mMapControls)}function zebraTables(){$("table tr:even").addClass("even");$("table tr:odd").addClass("odd")}$(function(){$("#accordion").accordion({autoHeight:!1});zebraTables()});function clearSearchResults(){myLayer=getLayerByName("scenes");if(!1!==myLayer){var a=myLayer.selectFeatureControl;a&&(a.deactivate(),myLayer.map.removeControl(a));myLayer.destroy()}}
function prepareFancy(){$("#accordion").accordion("activate",1);$("a#large_preview").fancybox({overlayShow:!1,imageScale:!0,zoomSpeedIn:600,zoomSpeedOut:500,easingIn:"easeOutBack",easingOut:"easeInBack",frameWidth:500,frameHeight:500})}
function showMiniCart(){myShowAccordionFlag=!0;1==arguments.length&&(myShowAccordionFlag=arguments[0]);if(myLayer=mMap.getLayersByName("Cart")[0])myLayer.mergeNewParams({seed:Math.random()}),myLayer.redraw(),$("#cart").load("/showminicartcontents/","",zebraTables),myShowAccordionFlag&&$("#accordion").accordion("activate",2),unblock()}function addToCart(a){block();$.get("/addtocart/"+a+"/?xhr","",showMiniCart);return!1}
function layerRemoved(){myLayer=mMap.getLayersByName("Cart")[0];myLayer.mergeNewParams({version:Math.random()});myLayer.redraw();return!1}
function removeFromCart(a,b){var c=$("#add_form #id_ref_id");if(0<c.length){var d=c.val(),d=d.length?d.split(","):[],e=b.parent().parent().find("a.show_form").attr("ref_id"),e=d.indexOf(e);-1<e&&(d.splice(e,1),c.val(d.join(",")))}$.get("/removefromcart/"+a+"/?xhr","",layerRemoved);b.parent().parent().remove();c=$("#cart-contents-table tr").length-1;$("#cart-item-count").html(c);1>c&&0!=$("#id_processing_level").length&&window.location.replace("/emptyCartHelp/");unblock();return!1}
function removeFromMiniCart(a,b){block();removeFromCart(a,b)}function showCart(){$("#cart").load("/showcartcontents/","",zebraTables);unblock()}function getElement(a){return document.getElementById?document.getElementById(a):document.all?document.all[a]:document.layers?document.layers[a]:0}function getFeatureByProductId(a){myLayer=getLayerByName("scenes");if(!1!==myLayer)for(var b=myLayer.features,c=0;c<b.length;++c)if(b[c].product_id==a)return c;return-1}
function revealTable(){zebraTables();unblock()}function loadPage(a,b){block();$("#page").parent().parent().load("/searchpage/"+b+"/?page="+a,"",revealTable)}function resizeTable(){myWindowHeight=$(window).height();myHeaderHeight=$("#header").height();myMapHeight=$("#map").height();myFooterHeight=$("#footer").height();myPadding=140;myTableHeight=myWindowHeight-(myHeaderHeight+myFooterHeight+myMapHeight+myPadding);200>myTableHeight&&(myTableHeight=200);$("#results").height(myTableHeight)}
function showFeatureInfo(a){block();myMousePos=mMap.getLonLatFromPixel(a.xy);myBoundingBox=mMap.getExtent().toBBOX();myPixelX=a.xy.x;myPixelY=a.xy.y;myMapWidth=mMap.size.w;myMapHeight=mMap.size.h;$("#mapquery").slideDown("slow");$("#hidemapquery").live("click",function(){$("#mapquery").slideUp("slow")});$.get("/getFeatureInfo/"+myMousePos.lon+"/"+myMousePos.lat+"/"+myBoundingBox+"/"+myPixelX+"/"+myPixelY+"/"+myMapWidth+"/"+myMapHeight+"/",function(a){$("#mapquery").html("<p><input type=button id='hidemapquery' value='Hide'></p>"+
a)});Event.stop(a);unblock()}function setHTML(a){$("#mapquery").html("<p><input type=button id='hidemapquery' value='Hide'></p>"+a.responseText);$("#mapquery").slideDown("slow");$("#hidemapquery").click(function(){$("#mapquery").slideUp("slow")})}var myMapHelpDialog=null,map_help_button=new OpenLayers.Control.Button({displayClass:"olControlMapHelp",trigger:function(){myMapHelpDialog.dialog("open")}});
function setupBaseMap(){var a={projection:new OpenLayers.Projection("EPSG:900913"),displayProjection:new OpenLayers.Projection("EPSG:4326"),units:"m",maxResolution:156543.0339,maxExtent:new OpenLayers.Bounds(-2.003750834E7,-2.003750834E7,2.003750834E7,2.003750834E7),numZoomLevels:18,controls:[]};mMap=new OpenLayers.Map("map",a);mNavigationPanel=new OpenLayers.Control.Panel({div:document.getElementById("map-navigation-panel")});a=new OpenLayers.Control.ZoomBox({title:"<b>Zoom in box</b> draw a box on the map, to see the area at a larger scale.",
displayClass:"olControlZoomBoxIn",out:!1});mMap.addControl(a);var b=new OpenLayers.Control.ZoomBox({title:"<b>Zoom out box</b> draw a box on the map, to see the area at a smaller scale.",displayClass:"olControlZoomBoxOut",out:!0});mMap.addControl(b);var c=new OpenLayers.Control.Navigation({title:"<b>Pan map</b> click and drag map to move the map in the direction of the mouse.",zoomWheelEnabled:!1});mMap.addControl(c);var d=new OpenLayers.Control.NavigationHistory({previousOptions:{title:"<b>Previous view</b> quickly jump to the prevoius map view."},
nextOptions:{title:"<b>Next view</b> quickly jump to the next map view, works only with prevoius view."}});mMap.addControl(d);mMap.addControl(map_help_button);mNavigationPanel.addControls([map_help_button,a,b,c,d.next,d.previous]);mMap.addControl(new OpenLayers.Control.ScaleBar({align:"left",minWidth:150,maxWidth:200,div:document.getElementById("map-scale")}));mMap.addControl(new OpenLayers.Control.MousePosition({div:document.getElementById("map-location")}));mMap.addControl(mNavigationPanel);mMap.addControl(new OpenLayers.Control.LayerSwitcher)}
function setupSearchMap(a){mWKTFormat=new OpenLayers.Format.WKT;setupBaseMap();mVectorLayer=new OpenLayers.Layer.Vector("search_geometry");mMap.addLayer(mVectorLayer);setupEditingPanel(mVectorLayer);mMap.addLayers(a);addSelectControl();(a=document.getElementById("id_geometry").value)?(a=readWKT(a),a=transformGeometry(a),writeWKT(a),mVectorLayer.addFeatures([new OpenLayers.Feature.Vector(a)]),mMap.zoomToExtent(a.getBounds())):(a=new OpenLayers.Bounds(16.3477,-35.2411,33.3984,-21.9727),a.transform(new OpenLayers.Projection("EPSG:4326"),
new OpenLayers.Projection("EPSG:900913")),mMap.zoomToExtent(a));mVectorLayer.events.on({featuremodified:modifyWKT});mVectorLayer.events.on({featureadded:addWKT});enableNavigation()}
function setupTaskingMap(a){mWKTFormat=new OpenLayers.Format.WKT;mVectorLayer=new OpenLayers.Layer.Vector("task_geometry");mMap.addLayer(mVectorLayer);setupEditingPanel(mVectorLayer);layerMapnik=new OpenLayers.Layer.OSM.Mapnik("Open Street Map");a.push(layerMapnik);mMap.addLayers(a);addSelectControl();if(a=document.getElementById("id_geometry").value){var b=readWKT(a),b=transformGeometry(b);writeWKT(b);mVectorLayer.addFeatures([new OpenLayers.Feature.Vector(b)]);mMap.zoomToExtent(b.getBounds())}else b=
new OpenLayers.Bounds(16.3477,-35.2411,33.3984,-21.9727),b.transform(new OpenLayers.Projection("EPSG:4326"),new OpenLayers.Projection("EPSG:900913")),mMap.zoomToExtent(b);mVectorLayer.events.on({featuremodified:modifyWKT});mVectorLayer.events.on({featureadded:addWKT});a?enableEditing():enableDrawing()}function featureSelected(a){block();$(".mapquery").html(a.feature.product_id);hightlightRecord(a.feature.id,!1);unblock()}
function setupSceneSelector(a){var b=new OpenLayers.Control.SelectFeature(a,{hover:!1,highlightOnly:!0,renderIntent:"temporary",eventListeners:{beforefeaturehighlighted:null,featurehighlighted:featureSelected,featureunhighlighted:null}});mMap.addControl(b);b.activate();a.selectFeatureControl=b}function deleteFeatures(){mVectorLayer.removeFeatures(mVectorLayer.features);mVectorLayer.destroyFeatures()}
function clearFeatures(){deleteFeatures();document.getElementById("id_geometry").value="";mMap.setCenter(transformPoint(new OpenLayers.LonLat(0,0)),4)}
function setupSearchFeatureInfo(){var a=new OpenLayers.Control.WMSGetFeatureInfo({url:"http://196.35.94.243/cgi-bin/mapserv?map=SEARCHES",title:"Identify features by clicking",queryVisible:!0,vendorParams:{FEATURE_COUNT:"1000",INFO_FORMAT:"text/html"},eventListeners:{getfeatureinfo:function(a){1<a.text.length?mMap.addPopup(new OpenLayers.Popup.FramedCloud("chicken",mMap.getLonLatFromPixel(a.xy),null,a.text,null,!0)):mMap.addPopup(new OpenLayers.Popup.FramedCloud("chicken",mMap.getLonLatFromPixel(a.xy),
null,"No result *sniff*",null,!0))}}});mMap.addControl(a);a.activate()}function setupSqlDialog(){$("#sql-button").live("click",function(){$("#sql").dialog({modal:!0,show:"slide",width:600,hide:"slide",autoOpen:!0,zIndex:9999,title:"Underlying Query:",buttons:{Close:function(){$(this).dialog("close")}}})})}
function setupSceneIdHelpDialog(){var a=$("<div></div>").load("/sceneidhelp/").dialog({autoOpen:!1,title:"Scene Id Help",modal:!0,show:"slide",hide:"slide",zIndex:9999,height:$(window).height()/2,width:$(window).width()/2,buttons:{Close:function(){$(this).dialog("close")}}});$("#scene-id-help").live("click",function(){a.dialog("open");return!1})}
function setupMapHelpDialog(){myMapHelpDialog=$("<div></div>").load("/mapHelp/").dialog({autoOpen:!1,title:"Map Help",modal:!0,show:"slide",hide:"slide",zIndex:9999,height:$(window).height()/2,width:$(window).width()/2,buttons:{Close:function(){$(this).dialog("close")}}})}
function showMetadata(a){$("<div></div>").load("/metadata/"+a+"/").dialog({autoOpen:!0,title:"Metadata",modal:!0,show:"slide",hide:"slide",zIndex:9999,height:$(window).height()/2,width:$(window).width()/2,buttons:{Close:function(){$(this).dialog("close")}}})}function setupMetadataDialog(){$(".metadata-icon").live("click",function(){var a=$(this).attr("longdesc");showMetadata(a)})}
function resetSceneZIndices(){myLayer=getLayerByName("scenes");if(!1!==myLayer)for(var a=myLayer.features,b=0;b<a.length;++b)a[b].attributes.zIndex=0,a[b].selected="no";return-1}function getFeatureIndexByRecordId(a){myLayer=getLayerByName("scenes");if(!1!==myLayer)for(var b=myLayer.features,c=0;c<b.length;++c)if(b[c].id==a)return c;return-1}
function hightlightRecord(a,b){mLastSelectedRecordId&&$("#record-"+mLastSelectedRecordId+" td").css("font-weight","normal");mLastSelectedRecordId=a;$("#record-"+a+" td").css("font-weight","bold");$("#preview-accordion-div").load("/showpreview/"+a+"/medium/","",prepareFancy);resetSceneZIndices();var c=getLayerByName("scenes"),d=getFeatureIndexByRecordId(a);c.features[d].attributes.zIndex=1;c.features[d].selected="yes";b&&mMap.zoomToExtent(c.features[d].geometry.bounds);c.redraw()}
function setupMiniIconClickCallback(){$(".mini-icon").live("click",function(){var a=$(this).attr("longdesc");hightlightRecord(a,!0)})}function setupRowClickCallback(){$(".result-row").live("click",function(){var a=$(this).attr("id").replace("record-","");hightlightRecord(a,!0)})}
function addOrderClicked(){2>$("#cart-contents-table tr").length?$("#cart-empty-dialog").dialog({modal:!0,show:"blind",hide:"explode",zIndex:99999,buttons:{Ok:function(){$(this).dialog("close")}}}):window.location.replace("/addorder/");return!1}function loadContent(a){block();$("#content").load(a,"",unblock)}function loadSummaryTable(a){block();$("#content").load("/sensorSummaryTable/"+a+"/","",unblock)}
function transformBounds(a){myBounds=a.clone();var a=new OpenLayers.Projection("EPSG:4326"),b=mMap.getProjectionObject()||new OpenLayers.Projection("EPSG:900913");myBounds.transform(a,b);return myBounds}function transformGeometry(a){myGeometry=a.clone();var a=new OpenLayers.Projection("EPSG:4326"),b=mMap.getProjectionObject()||new OpenLayers.Projection("EPSG:900913");myGeometry.transform(a,b);return myGeometry}
function reverseTransformGeometry(a){myGeometry=a.clone();a=new OpenLayers.Projection("EPSG:4326");myGeometry.transform(mMap.getProjectionObject(),a);return myGeometry}function transformPoint(a){var b=new OpenLayers.Projection("EPSG:4326"),c=new OpenLayers.Projection("EPSG:900913");myPoint=a.clone();return myPoint=myPoint.transform(b,c)}
function reverseTransformPoint(a){var b=new OpenLayers.Projection("EPSG:4326"),c=new OpenLayers.Projection("EPSG:900913");myPoint=a.clone();return myPoint=myPoint.transform(c,b)};