# Generated by Django 2.2.28 on 2025-02-14 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import userena.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SansaUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mugshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='A personal image displayed in your profile.', upload_to=userena.models.upload_to_mugshot, verbose_name='mugshot')),
                ('privacy', models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='closed', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy')),
                ('strategic_partner', models.BooleanField(default=False, help_text='Mark this as true if the person belongs to an institution that is a CSIR/SAC strategic partner', verbose_name='Strategic Partner?')),
                ('url', models.URLField(blank=True, verbose_name='Your website url')),
                ('about', models.TextField(blank=True)),
                ('address1', models.CharField(max_length=255, verbose_name='Address 1 (required)')),
                ('address2', models.CharField(max_length=255, verbose_name='Address 2 (required)')),
                ('address3', models.CharField(blank=True, max_length=255)),
                ('address4', models.CharField(blank=True, max_length=255)),
                ('post_code', models.CharField(max_length=25, verbose_name='Post Code (required)')),
                ('organisation', models.CharField(max_length=255, verbose_name='Organisation (required)')),
                ('contact_no', models.CharField(max_length=16, verbose_name='Contact No (required)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sansauserprofile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'permissions': (('view_profile', 'Can view profile'),),
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
    ]
