# Generated by Django 2.2.28 on 2023-06-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satelliteinstrumentgroup',
            name='end_date',
            field=models.DateField(blank=True, help_text='The end date to hide the data from the user in the search page', null=True),
        ),
        migrations.AddField(
            model_name='satelliteinstrumentgroup',
            name='is_searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='satelliteinstrumentgroup',
            name='start_date',
            field=models.DateField(blank=True, help_text='The beginning date to hide the data from the user in the search page', null=True),
        ),
    ]
