# Generated by Django 2.2.28 on 2025-03-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20230606_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumenttype',
            name='scanner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionaries.ScannerType'),
        ),
        migrations.AlterField(
            model_name='opticalproductprofile',
            name='spectral_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionaries.SpectralMode'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Collection'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='license_type',
            field=models.ForeignKey(blank=True, help_text='Satellite product license type', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionaries.License'),
        ),
    ]
