# Generated by Django 2.2.27 on 2022-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uses',
            field=models.CharField(blank=True, help_text='Please tell us the uses of the data', max_length=500, null=True),
        ),
    ]
