-- Run this on the acs db to clear out django / catalogue tables
drop table catalogue_genericproduct cascade;
drop table catalogue_opticalproduct cascade;
drop table auth_user cascade;
drop table auth_group cascade;
drop table auth_group_permissions cascade;
drop table auth_message cascade;
drop table auth_permission cascade;
drop table auth_user_groups cascade;
drop table auth_user_user_permissions cascade;
drop table catalogue_visit;
drop table catalogue_visit cascade;
drop table django_admin_log cascade;
drop table django_content_type;
drop table django_site;
drop table django_session;
drop table userprofile_avatar;
drop table userprofile_emailvalidation;
drop table catalogue_acquisitionmode cascade;
drop table catalogue_clip  cascade;
drop table catalogue_creatingsoftware  cascade;
drop table catalogue_datum            cascade;
drop table catalogue_deliverymethod  cascade;
drop table catalogue_fileformat     cascade;
drop table catalogue_institution cascade;
drop table catalogue_license cascade;
drop table catalogue_mission cascade;
drop table catalogue_missionsensor cascade;
drop table catalogue_opticalproduct cascade;
drop table catalogue_order cascade;
drop table catalogue_orderstatus cascade;
drop table catalogue_orderstatushistory cascade;
drop table catalogue_processinglevel cascade;
drop table catalogue_projection cascade;
drop table catalogue_quality cascade;
drop table catalogue_radarproduct cascade;
drop table catalogue_resamplingmethod cascade;
drop table catalogue_sacuserprofile cascade;
drop table catalogue_search cascade;
drop table catalogue_searchrecord cascade;
drop table catalogue_sensor_type cascade;
drop table catalogue_sensortype cascade;
drop table clip  cascade;
drop table orderstatus  cascade;
drop table orderstatushistory  cascade;
drop table registration_registrationprofile   cascade;
drop table rowpath  cascade;
drop table search  cascade;
drop table visit  cascade;
drop view vw_visitor_report cascade;
vacuum analyze;
